<a href="https://colab.research.google.com/github/Diwash17/5CS037_2407736_2024_Diwash_Adhikari/blob/main/Diwash_Adhikari_worksheet1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [57]:
import numpy as np

In [58]:
np.empty((2,2))

array([[1.14e-322, 6.42e-323],
       [2.52e-322, 1.43e-322]])

In [59]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [60]:
np.full((4,2),4)

array([[4, 4],
       [4, 4],
       [4, 4],
       [4, 4]])

In [61]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [62]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [63]:
new_list=[1,2,3,4]
num_arrr=np.array(new_list)

In [64]:
num_arrr

array([1, 2, 3, 4])

In [65]:
np.arange(1,50)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [66]:

values = np.arange(9)

matrix = values.reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [67]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [68]:
random_number=np.random.random(30)

In [69]:
random_number

array([3.30122740e-01, 3.73712081e-01, 6.01392644e-01, 2.52683309e-02,
       7.66079762e-01, 7.36109687e-01, 7.05294438e-01, 7.84368243e-02,
       9.23477431e-01, 9.75973450e-01, 7.89228565e-01, 5.91662267e-01,
       4.09531317e-01, 8.38663086e-01, 1.39085590e-01, 9.41322633e-01,
       1.10558651e-02, 2.61812637e-01, 3.90864631e-05, 3.88950849e-01,
       8.17618900e-01, 9.49034639e-01, 4.60146004e-02, 5.45399860e-03,
       1.42869468e-03, 1.57900728e-01, 9.39361590e-01, 5.12922904e-01,
       3.84248439e-01, 5.75243471e-01])

In [70]:
random_number.mean()

0.47588157495329586

In [71]:
rand_num=np.random.random((10,10))

In [72]:
rand_num

array([[0.40142179, 0.84523335, 0.29046245, 0.1817308 , 0.49888287,
        0.67614903, 0.36126386, 0.24733124, 0.46274869, 0.5762126 ],
       [0.66472675, 0.20584434, 0.70080239, 0.74252296, 0.37400703,
        0.26834073, 0.55053143, 0.44644977, 0.28296178, 0.60455011],
       [0.6881182 , 0.15174662, 0.66824754, 0.78851833, 0.85663813,
        0.92669264, 0.37144136, 0.73621611, 0.96537362, 0.26655717],
       [0.91284611, 0.10226806, 0.92801275, 0.46665787, 0.09662472,
        0.84512471, 0.39807169, 0.19620662, 0.8352492 , 0.36965002],
       [0.9396845 , 0.81514371, 0.9576055 , 0.86884426, 0.20296261,
        0.8238652 , 0.01844398, 0.07696371, 0.42813736, 0.20789617],
       [0.06363567, 0.24831103, 0.99914453, 0.74441063, 0.55107367,
        0.85724373, 0.95565892, 0.74334548, 0.81254727, 0.84479625],
       [0.28656895, 0.663326  , 0.16619993, 0.01076336, 0.53484593,
        0.36773865, 0.61656801, 0.63909788, 0.43412915, 0.3776456 ],
       [0.36824418, 0.1669533 , 0.8173687

In [73]:
rand_num.max()

0.9991445340348779

In [74]:
rand_num.min()

0.009252150713740193

In [75]:
new_arr=np.zeros(10)

In [76]:
new_arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [77]:
new_arr[4]=1

In [78]:
new_arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [79]:
arr = [1,2,0,0,4,0]

In [80]:
arr.reverse()

In [81]:
arr

[0, 4, 0, 0, 2, 1]

In [82]:
n = 8
array = np.ones((n, n), dtype=int)
array[1:-1, 1:-1] = 0

In [83]:
array

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [84]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

In [85]:
checkerboard

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [86]:
x = np.array([[1,2],[3,5]])
y=np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])


In [87]:
x+y

array([[ 6,  8],
       [10, 13]])

In [88]:
x-y

array([[-4, -4],
       [-4, -3]])

In [89]:
x*5

array([[ 5, 10],
       [15, 25]])

In [90]:
x**2

array([[ 1,  4],
       [ 9, 25]])

In [91]:
print(np.dot(v, w))
print(np.dot(x, v))
print(np.dot(x, y))

219
[29 77]
[[19 22]
 [50 58]]


In [92]:
np.concatenate((x,y))

array([[1, 2],
       [3, 5],
       [5, 6],
       [7, 8]])

In [93]:
np.hstack((x,y))

array([[1, 2, 5, 6],
       [3, 5, 7, 8]])

In [94]:
np.vstack((v,w))

array([[ 9, 10],
       [11, 12]])

In [95]:
np.concatenate((x,v))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [96]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

In [97]:
A_inverse=np.linalg.inv(A)

In [98]:
B_inverse=np.linalg.inv(B)

In [99]:
result=np.dot(A,A_inverse)
I = np.eye(A.shape[0])
is_identity = np.allclose(result, I)

In [100]:
result

array([[1.00000000e+00, 0.00000000e+00],
       [1.77635684e-15, 1.00000000e+00]])

In [101]:
is_identity

True

In [102]:

AB = np.dot(A, B)  # or A @ B
BA = np.dot(B, A)  # or B @ A


print("AB:", AB)
print("BA:", BA)


are_equal = np.array_equal(AB, BA)
print("Is AB equal to BA? ", are_equal)

AB: [[23 13]
 [51 29]]
BA: [[36 44]
 [13 16]]
Is AB equal to BA?  False


In [103]:
AB = np.dot(A, B)
AB_T = AB.T

B_T = B.T
A_T = A.T
B_T_A_T = np.dot(B_T, A_T)

are_equal = np.array_equal(AB_T, B_T_A_T)

print("(AB)^T:", AB_T)
print("B^T A^T:", B_T_A_T)
print("Is (AB)^T equal to B^T A^T? ", are_equal)

(AB)^T: [[23 51]
 [13 29]]
B^T A^T: [[23 51]
 [13 29]]
Is (AB)^T equal to B^T A^T?  True


In [104]:
import time

list1, list2 = range(1_000_000), range(1_000_000)
start = time.time()
list_sum = [x + y for x, y in zip(list1, list2)]
time_list = time.time() - start

array1, array2 = np.arange(1_000_000), np.arange(1_000_000)
start = time.time()
array_sum = array1 + array2
time_numpy = time.time() - start

print(f"Python lists: {time_list:.3f}s, NumPy arrays: {time_numpy:.3f}s")

Python lists: 0.114s, NumPy arrays: 0.004s


In [105]:
list1, list2 = range(1_000_000), range(1_000_000)

start = time.time()
list_product = [x * y for x, y in zip(list1, list2)]
time_list = time.time() - start

array1, array2 = np.arange(1_000_000), np.arange(1_000_000)

start = time.time()
array_product = array1 * array2
time_numpy = time.time() - start

print(f"Python lists: {time_list:.3f}s, NumPy arrays: {time_numpy:.3f}s")

Python lists: 0.122s, NumPy arrays: 0.003s


In [109]:
import random
size = 1000000

list1 = [random.random() for _ in range(size)]
list2 = [random.random() for _ in range(size)]

start_time = time.time()
dot_product = sum(a * b for a, b in zip(list1, list2))
end_time = time.time()
list_time = end_time - start_time
print(f"Time taken with Python lists: {list_time:.4f} seconds")
print(f"Dot product with lists: {dot_product}")

array1 = np.array(list1)
array2 = np.array(list2)

start_time = time.time()
dot_product_np = np.dot(array1, array2)
end_time = time.time()
numpy_time = end_time - start_time
print(f"\nTime taken with NumPy: {numpy_time:.4f} seconds")
print(f"Dot product with NumPy: {dot_product_np}")

print(f"\nNumPy is {list_time/numpy_time:.1f}x faster than Python lists")

Time taken with Python lists: 0.0830 seconds
Dot product with lists: 249802.80049820544

Time taken with NumPy: 0.0014 seconds
Dot product with NumPy: 249802.80049820154

NumPy is 58.3x faster than Python lists


In [107]:
size = 1000

matrix1 = [[1] * size for _ in range(size)]
matrix2 = [[1] * size for _ in range(size)]
result = [[0] * size for _ in range(size)]

start_time = time.time()
for i in range(size):
    for j in range(size):
        result[i][j] = sum(matrix1[i][k] * matrix2[k][j] for k in range(size))
end_time = time.time()
print(f"Time taken using Python lists: {end_time - start_time:.2f} seconds")

matrix1_np = np.ones((size, size))
matrix2_np = np.ones((size, size))

start_time = time.time()
result_np = np.dot(matrix1_np, matrix2_np)
end_time = time.time()
print(f"Time taken using NumPy: {end_time - start_time:.2f} seconds")

Time taken using Python lists: 181.05 seconds
Time taken using NumPy: 0.06 seconds
