<a href="https://colab.research.google.com/github/Diwash17/5CS037_2407736_2024_Diwash_Adhikari/blob/main/Diwash_Adhikari_worksheet1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
np.empty((2,2))

array([[ 4.87723657e-310,  0.00000000e+000],
       [-9.31715264e+095,  6.88438222e-310]])

In [4]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [5]:
np.full((4,2),4)

array([[4, 4],
       [4, 4],
       [4, 4],
       [4, 4]])

In [6]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [7]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
new_list=[1,2,3,4]
num_arrr=np.array(new_list)

In [9]:
num_arrr

array([1, 2, 3, 4])

In [10]:
np.arange(1,50)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [11]:

values = np.arange(9)

matrix = values.reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
random_number=np.random.random(30)

In [14]:
random_number

array([0.55100898, 0.36016672, 0.61148045, 0.64064147, 0.8818841 ,
       0.07060142, 0.09399604, 0.19656977, 0.70959823, 0.71522754,
       0.55433551, 0.49129457, 0.94790796, 0.60123945, 0.15425006,
       0.87504704, 0.04285309, 0.0571196 , 0.27872487, 0.51924664,
       0.49056669, 0.69935809, 0.44575305, 0.66013042, 0.20626168,
       0.3860795 , 0.45100599, 0.90330795, 0.62598701, 0.31161426])

In [15]:
random_number.mean()

0.4844419390501009

In [16]:
rand_num=np.random.random((10,10))

In [17]:
rand_num

array([[0.74404056, 0.48340965, 0.05670455, 0.39506618, 0.54661912,
        0.77705209, 0.04016106, 0.41582014, 0.45814103, 0.39742766],
       [0.48331252, 0.1566095 , 0.93318202, 0.82940329, 0.54377748,
        0.62077679, 0.28656918, 0.39863808, 0.1766987 , 0.99292224],
       [0.72348665, 0.7406709 , 0.52494953, 0.29530419, 0.11383705,
        0.78063866, 0.30167675, 0.00761915, 0.34122279, 0.14091801],
       [0.07507471, 0.4736842 , 0.31650062, 0.4361604 , 0.78711639,
        0.75204665, 0.71171468, 0.70038925, 0.61029502, 0.95171333],
       [0.19649152, 0.56355696, 0.99747662, 0.62510551, 0.43292672,
        0.6387171 , 0.86560721, 0.82128113, 0.01739505, 0.6475812 ],
       [0.47415838, 0.42990523, 0.15480525, 0.83055589, 0.66280697,
        0.98103184, 0.02383329, 0.4134977 , 0.45654729, 0.00912245],
       [0.52955256, 0.35679355, 0.75510034, 0.34635584, 0.91768148,
        0.24245092, 0.80387431, 0.61496335, 0.69486765, 0.00816693],
       [0.88685729, 0.66292054, 0.6509721

In [18]:
rand_num.max()

0.9993031229624708

In [19]:
rand_num.min()

0.007619150162029964

In [20]:
new_arr=np.zeros(10)

In [21]:
new_arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
new_arr[4]=1

In [23]:
new_arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [24]:
arr = [1,2,0,0,4,0]

In [25]:
arr.reverse()

In [26]:
arr

[0, 4, 0, 0, 2, 1]

In [27]:
x = np.array([[1,2],[3,5]])
y=np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])


In [28]:
x+y

array([[ 6,  8],
       [10, 13]])

In [29]:
x-y

array([[-4, -4],
       [-4, -3]])

In [30]:
x*5

array([[ 5, 10],
       [15, 25]])

In [31]:
x**2

array([[ 1,  4],
       [ 9, 25]])

In [32]:
print(np.dot(v, w))
print(np.dot(x, v))
print(np.dot(x, y))

219
[29 77]
[[19 22]
 [50 58]]


In [33]:
np.concatenate((x,y))

array([[1, 2],
       [3, 5],
       [5, 6],
       [7, 8]])

In [34]:
np.hstack((x,y))

array([[1, 2, 5, 6],
       [3, 5, 7, 8]])

In [35]:
np.vstack((v,w))

array([[ 9, 10],
       [11, 12]])

In [36]:
np.concatenate((x,v))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [37]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

In [38]:
A_inverse=np.linalg.inv(A)

In [39]:
B_inverse=np.linalg.inv(B)

In [40]:
result=np.dot(A,A_inverse)
I = np.eye(A.shape[0])
is_identity = np.allclose(result, I)

In [41]:
result

array([[1.00000000e+00, 0.00000000e+00],
       [1.77635684e-15, 1.00000000e+00]])

In [42]:
is_identity

True

In [43]:

AB = np.dot(A, B)  # or A @ B
BA = np.dot(B, A)  # or B @ A


print("AB:", AB)
print("BA:", BA)


are_equal = np.array_equal(AB, BA)
print("Is AB equal to BA? ", are_equal)

AB: [[23 13]
 [51 29]]
BA: [[36 44]
 [13 16]]
Is AB equal to BA?  False


In [44]:
AB = np.dot(A, B)
AB_T = AB.T

B_T = B.T
A_T = A.T
B_T_A_T = np.dot(B_T, A_T)

are_equal = np.array_equal(AB_T, B_T_A_T)

print("(AB)^T:", AB_T)
print("B^T A^T:", B_T_A_T)
print("Is (AB)^T equal to B^T A^T? ", are_equal)

(AB)^T: [[23 51]
 [13 29]]
B^T A^T: [[23 51]
 [13 29]]
Is (AB)^T equal to B^T A^T?  True


In [47]:
import time

list1, list2 = range(1_000_000), range(1_000_000)
start = time.time()
list_sum = [x + y for x, y in zip(list1, list2)]
time_list = time.time() - start

array1, array2 = np.arange(1_000_000), np.arange(1_000_000)
start = time.time()
array_sum = array1 + array2
time_numpy = time.time() - start

print(f"Python lists: {time_list:.3f}s, NumPy arrays: {time_numpy:.3f}s")

Python lists: 0.396s, NumPy arrays: 0.012s


In [49]:
list1, list2 = range(1_000_000), range(1_000_000)

start = time.time()
list_product = [x * y for x, y in zip(list1, list2)]
time_list = time.time() - start

array1, array2 = np.arange(1_000_000), np.arange(1_000_000)

start = time.time()
array_product = array1 * array2
time_numpy = time.time() - start

print(f"Python lists: {time_list:.3f}s, NumPy arrays: {time_numpy:.3f}s")

Python lists: 0.223s, NumPy arrays: 0.005s
